In [13]:
import keras.optimizers
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import Supervise_ML as sml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import tensorflow as tf
from keras.models import Sequential, load_model
from keras.layers import Dense, Input, Normalization
from keras.losses import MeanSquaredError, BinaryCrossentropy
from keras.optimizers import Adam
from keras.activations import sigmoid

# from tensorflow.keras.models import Sequential, load_model
# from tensorflow.keras.layers import Dense

import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

In [5]:
X, y = sml.load_coffee_data()
X

array([[185.31763812,  12.69396457],
       [259.92047498,  11.86766377],
       [231.01357101,  14.41424211],
       [175.3666449 ,  11.72058651],
       [187.12086467,  14.12973206],
       [225.90586448,  12.10024905],
       [208.40515676,  14.17718919],
       [207.07593089,  14.0327376 ],
       [280.60385359,  14.23225929],
       [202.86935247,  12.24901028],
       [196.70468985,  13.54426389],
       [270.31327028,  14.60225577],
       [192.94979108,  15.19686759],
       [213.57283453,  14.27503537],
       [164.47298664,  11.91817423],
       [177.25750542,  15.03779869],
       [241.7745473 ,  14.89694529],
       [236.99889634,  13.12616959],
       [219.73805621,  13.87377407],
       [266.38592796,  13.25274466],
       [270.45241485,  13.95486775],
       [261.96307698,  13.49222422],
       [243.4899478 ,  12.8561015 ],
       [220.58184803,  12.36489356],
       [163.59498627,  11.65441652],
       [244.76317931,  13.32572248],
       [271.19410986,  14.84073282],
 

In [6]:
#Creating a normalization layer
norm1 = Normalization(axis=-1)
norm1.adapt(X)
Xn = norm1(X)
Xn

<tf.Tensor: shape=(200, 2), dtype=float32, numpy=
array([[-0.8345551 , -0.6528792 ],
       [ 1.0323051 , -1.3851453 ],
       [ 0.3089391 ,  0.8716251 ],
       [-1.0835688 , -1.5154841 ],
       [-0.7894313 ,  0.6194935 ],
       [ 0.18112417, -1.1790283 ],
       [-0.25681356,  0.6615495 ],
       [-0.29007602,  0.5335373 ],
       [ 1.5498857 ,  0.7103532 ],
       [-0.39534125, -1.047197  ],
       [-0.54960555,  0.1006532 ],
       [ 1.2923743 ,  1.0382426 ],
       [-0.6435681 ,  1.5651861 ],
       [-0.12749763,  0.7482604 ],
       [-1.3561714 , -1.340383  ],
       [-1.0362518 ,  1.4242196 ],
       [ 0.57822186,  1.2993953 ],
       [ 0.45871606, -0.26986104],
       [ 0.02678081,  0.3926646 ],
       [ 1.1940966 , -0.15769024],
       [ 1.2958566 ,  0.46452886],
       [ 1.0834192 ,  0.05453626],
       [ 0.6211478 , -0.5091947 ],
       [ 0.04789595, -0.94450104],
       [-1.3781425 , -1.5741245 ],
       [ 0.65300936, -0.09301733],
       [ 1.3144168 ,  1.24958   ],
     

In [7]:
Xt = np.tile(Xn,(1000,1))
yt = np.tile(y,(1000,1))

In [8]:
tf.random.set_seed(1234)
model = Sequential(
    [
        Input(shape=(2,)),
        Dense(units=3,activation='sigmoid',name='layer1'),
        Dense(units=1,activation='sigmoid',name='layer2')
    ]
)

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 3)                 9         
                                                                 
 layer2 (Dense)              (None, 1)                 4         
                                                                 
Total params: 13 (52.00 Byte)
Trainable params: 13 (52.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
L1_num_params = 2 * 3 + 3   # W1 parameters  + b1 parameters
L2_num_params = 3 * 1 + 1   # W2 parameters  + b2 parameters
print("L1 params = ", L1_num_params, ", L2 params = ", L2_num_params  )

L1 params =  9 , L2 params =  4


In [11]:
w1, b1 = model.get_layer('layer1').get_weights()
w2, b2 = model.get_layer('layer2').get_weights()
print(w2,b1,w2,b2)

[[0.14107788]
 [1.1900433 ]
 [0.19791222]] [0. 0. 0.] [[0.14107788]
 [1.1900433 ]
 [0.19791222]] [0.]


In [28]:
model.compile(loss='binary_crossentropy',optimizer=Adam(learning_rate=0.01))
yt

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [1.],
       [0.]])

In [19]:
model.fit(Xt,yt,epochs=2)

Epoch 1/2
6250/6250 [==============================] - 15s 2ms/step - loss: 0.1164
Epoch 2/2
6250/6250 [==============================] - 12s 2ms/step - loss: 0.0480


In [21]:
w1, b1 = model.get_layer("layer1").get_weights()
w2, b2 = model.get_layer("layer2").get_weights()
print(w1,b1,w2,b2)

[[ 0.4970613  8.256825  11.387441 ]
 [-5.936673  -0.0476109  9.631878 ]] [-7.637369   8.548908   0.6077497] [[-16.971155]
 [ 15.379133]
 [-22.79043 ]] [-5.82439]


In [22]:
# After finishing the lab later, you can re-run all 
# cells except this one to see if your trained model
# gets the same results.

# Set weights from a previous run. 
W1 = np.array([
    [-8.94,  0.29, 12.89],
    [-0.17, -7.34, 10.79]] )
b1 = np.array([-9.87, -9.28,  1.01])
W2 = np.array([
    [-31.38],
    [-27.86],
    [-32.79]])
b2 = np.array([15.54])

# Replace the weights from your trained model with
# the values above.
model.get_layer("layer1").set_weights([W1,b1])
model.get_layer("layer2").set_weights([W2,b2])

In [23]:
# Check if the weights are successfully replaced
W1, b1 = model.get_layer("layer1").get_weights()
W2, b2 = model.get_layer("layer2").get_weights()
print("W1:\n", W1, "\nb1:", b1)
print("W2:\n", W2, "\nb2:", b2)

W1:
 [[-8.94  0.29 12.89]
 [-0.17 -7.34 10.79]] 
b1: [-9.87 -9.28  1.01]
W2:
 [[-31.38]
 [-27.86]
 [-32.79]] 
b2: [15.54]


In [24]:
X_test = np.array([[200,13.9],[200,17]])
X_testn = norm1(X_test)
X_testn

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.46714395,  0.4159052 ],
       [-0.46714395,  3.1631167 ]], dtype=float32)>

In [25]:
pred = model.predict(X_testn)
pred

1/1 [==============================] - 0s 164ms/step


array([[9.625139e-01],
       [3.031606e-08]], dtype=float32)

In [27]:
y_pred = (pred >= 0.5).astype(int)
y_pred

array([[1],
       [0]])