In [6]:
import numpy as np
import tensorflow as tf
from keras.layers import Dense
from keras.models import Sequential
from sklearn.datasets import make_blobs
from keras.optimizers import Adam
from keras.losses import SparseCategoricalCrossentropy as scc
#pip install -U tensorflow

In [13]:
def manual_softmax(z):
    ez = np.exp(z)
    sumo = ez/np.sum(ez)
    return sumo

In [7]:
# make  dataset for example
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

In [11]:
model = Sequential([Dense(25,activation='relu'),Dense(15,activation='relu'),Dense(4,activation='softmax')])
model.compile(loss=scc(),optimizer=Adam(0.001))
model.fit(X_train,y_train,epochs=20)

Epoch 1/20
63/63 [==============================] - 1s 2ms/step - loss: 0.7542
Epoch 2/20
63/63 [==============================] - 0s 2ms/step - loss: 0.2983
Epoch 3/20
63/63 [==============================] - 0s 2ms/step - loss: 0.1240
Epoch 4/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0762
Epoch 5/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0604
Epoch 6/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0522
Epoch 7/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0476
Epoch 8/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0434
Epoch 9/20
63/63 [==============================] - 0s 3ms/step - loss: 0.0408
Epoch 10/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0380
Epoch 11/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0358
Epoch 12/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0338
Epoch 13/20
63/63 [==============================

In [12]:
model.predict(X_train)

63/63 [==============================] - 0s 1ms/step


array([[1.1408502e-04, 1.0329026e-03, 9.9680650e-01, 2.0465869e-03],
       [9.9645633e-01, 3.5358246e-03, 7.7078967e-06, 7.1818498e-08],
       [9.6436203e-01, 3.5454672e-02, 1.8003394e-04, 3.3145784e-06],
       ...,
       [3.7981261e-04, 9.9689484e-01, 2.3221031e-03, 4.0326521e-04],
       [1.1931725e-08, 2.5058832e-06, 3.4397173e-05, 9.9996305e-01],
       [5.3213508e-04, 1.1111953e-03, 9.9767119e-01, 6.8550918e-04]],
      dtype=float32)

In [14]:
preferred_model = Sequential([Dense(25,activation='relu'),Dense(15,activation='relu'),Dense(4,activation='linear')])
preferred_model.compile(optimizer=Adam(0.001),loss=scc(from_logits=True))
preferred_model.fit(X_train,y_train,epochs=20)

Epoch 1/20
63/63 [==============================] - 1s 2ms/step - loss: 0.7919
Epoch 2/20
63/63 [==============================] - 0s 2ms/step - loss: 0.3174
Epoch 3/20
63/63 [==============================] - 0s 2ms/step - loss: 0.1573
Epoch 4/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0994
Epoch 5/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0754
Epoch 6/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0633
Epoch 7/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0558
Epoch 8/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0513
Epoch 9/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0474
Epoch 10/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0443
Epoch 11/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0418
Epoch 12/20
63/63 [==============================] - 0s 2ms/step - loss: 0.0395
Epoch 13/20
63/63 [==============================

In [15]:
output = model.predict(X_train)
output

63/63 [==============================] - 0s 1ms/step


array([[1.1408502e-04, 1.0329026e-03, 9.9680650e-01, 2.0465869e-03],
       [9.9645633e-01, 3.5358246e-03, 7.7078967e-06, 7.1818498e-08],
       [9.6436203e-01, 3.5454672e-02, 1.8003394e-04, 3.3145784e-06],
       ...,
       [3.7981261e-04, 9.9689484e-01, 2.3221031e-03, 4.0326521e-04],
       [1.1931725e-08, 2.5058832e-06, 3.4397173e-05, 9.9996305e-01],
       [5.3213508e-04, 1.1111953e-03, 9.9767119e-01, 6.8550918e-04]],
      dtype=float32)

In [16]:
tf.nn.softmax(output).numpy()

array([[0.17506514, 0.17522608, 0.47430497, 0.17540379],
       [0.4741883 , 0.1756835 , 0.17506476, 0.17506342],
       [0.4634978 , 0.1830747 , 0.17672938, 0.17669816],
       ...,
       [0.17510703, 0.4743343 , 0.17544748, 0.17511114],
       [0.17487966, 0.1748801 , 0.17488568, 0.47535458],
       [0.17509307, 0.1751945 , 0.47459254, 0.17511994]], dtype=float32)